object FormMain: TFormMain
  Left = 0
  Top = 0
  Caption = 'FormMain'
  ClientHeight = 617
  ClientWidth = 791
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  TextHeight = 15
  object Panel1: TPanel
    Left = 120
    Top = 48
    Width = 529
    Height = 497
    TabOrder = 0
    object btnEstudantes: TButton
      AlignWithMargins = True
      Left = 61
      Top = 122
      Width = 407
      Height = 44
      Margins.Left = 60
      Margins.Top = 70
      Margins.Right = 60
      Margins.Bottom = 330
      Align = alClient
      Caption = 'Estudantes'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      ExplicitLeft = 13
      ExplicitTop = 51
      ExplicitHeight = 55
    end
    object btnProfessores: TButton
      AlignWithMargins = True
      Left = 61
      Top = 192
      Width = 407
      Height = 44
      Margins.Left = 60
      Margins.Top = 140
      Margins.Right = 60
      Margins.Bottom = 260
      Align = alClient
      Caption = 'Professores'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      ExplicitLeft = 173
      ExplicitTop = 122
    end
    object btnDisciplinas: TButton
      AlignWithMargins = True
      Left = 61
      Top = 262
      Width = 407
      Height = 44
      Margins.Left = 60
      Margins.Top = 210
      Margins.Right = 60
      Margins.Bottom = 190
      Align = alClient
      Caption = 'Disciplinas'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      ExplicitLeft = 149
      ExplicitTop = 141
      ExplicitHeight = 55
    end
    object btnTurmas: TButton
      AlignWithMargins = True
      Left = 61
      Top = 332
      Width = 407
      Height = 44
      Margins.Left = 60
      Margins.Top = 280
      Margins.Right = 60
      Margins.Bottom = 120
      Align = alClient
      Caption = 'Turmas'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      ExplicitLeft = 69
      ExplicitTop = 219
      ExplicitHeight = 55
    end
    object btnMatriculas: TButton
      AlignWithMargins = True
      Left = 61
      Top = 402
      Width = 407
      Height = 44
      Margins.Left = 60
      Margins.Top = 350
      Margins.Right = 60
      Margins.Bottom = 50
      Align = alClient
      Caption = 'Matriculas'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      ExplicitLeft = 197
      ExplicitTop = 71
      ExplicitHeight = 55
    end
    object StaticText1: TStaticText
      AlignWithMargins = True
      Left = 101
      Top = 16
      Width = 327
      Height = 36
      Margins.Left = 100
      Margins.Top = 15
      Margins.Right = 100
      Margins.Bottom = 0
      Align = alTop
      Alignment = taCenter
      Caption = 'Menu Principal'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 5
      ExplicitWidth = 227
    end
  end
end
